[package]
name = "fdp-sys"
version = "0.1.0"
authors = ["Mathieu Tarral <mathieu.tarral@protonmail.com>"]
edition = "2018"
links = "FDP"
repository = "https://github.com/Wenzel/fdp-sys"
readme = "README.md"
keywords = ["Winbagility", "FDP", "VirtualBox", "VMI"]
description = "Rust unsafe bindings for FDP (Fast Debugging Protocol)"
license = "GPL-3.0-only"

[dependencies]

[build-dependencies]
bindgen = "0.49.2"
